#pragma once

#include "CoreMinimal.h"

//// [ignore]
#ifdef OVERRIDE_SYSTEMS_ARCHETYPE_BUCKETS_COUNT
const uint32 SYSTEMS_ARCHETYPE_BUCKETS_COUNT =
	OVERRIDE_SYSTEMS_ARCHETYPE_BUCKETS_COUNT;
#else
const uint32 SYSTEMS_ARCHETYPE_BUCKETS_COUNT = 8;
#endif
const uint32 SYSTEMS_COMPONENTS_COUNT = 32 * SYSTEMS_ARCHETYPE_BUCKETS_COUNT;
//// [/ignore]
