name: github pages

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Install unreal-doc
        run: cargo install unreal-doc
      - name: Show unreal-doc version
        run: unreal-doc --version
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - name: Show mdbook version
        run: mdbook --version
      - name: Bake Systems Architecture docs
        run: UNREAL_DOC_MDBOOK_SITE_URL="https://psichix.github.io/Unreal-Systems-Architecture/systems/" unreal-doc -i ./Plugins/Systems/Documentation/UnrealDoc.toml
      - name: Setup output location
        run: mkdir ./PublicDocs
      - name: Move Systems Architecture docs to output location
        run: mv -f ./Plugins/Systems/Documentation/Distribution/book ./PublicDocs/systems
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./PublicDocs